  stages:
    - texdocs

  check:
    only:
      - main
#    refs:
#      - master
#      - merge_requests
    tags:
      - mkdocs
    rules:
      - exists:
        - material
    stage: texdocs
    script:
      - echo exist

  build:
    only:
      - main
#    refs:
#      - master
#      - merge_requests
    tags:
      - mkdocs
    stage: texdocs
    script:
      - echo $CI_PROJECT_NAME
      - pwd
      - ls -alZ
      - hostname -f
      - whoami & id
