stages:
  - deploy

variables:
  VIRT_SITE_NAME: "Настройка ansible pull"

check:
  stage: .pre
  tags:
    - mkdocs
  rules:
    - exists:
        - material/mkdocs_theme.yml
      when: never
    - when: always
  script:
    - echo "not exist"

deploy:
  stage: deploy
  only:
    - main
  tags:
    - mkdocs
  script:
    - cd $CI_PROJECT_DIR && sudo -u mkdocs /var/mkdocs/.local/bin/mkdocs build -c -f texdocs.yml -d "/var/www/base/docs/$VIRT_SITE_NAME"
