  stages:
    - texdocs

  .check_rule:
    rules:
      - exists:
        - material

  check:
    tags:
      - mkdocs
    stage: texdocs
    script:
      - echo exist
      - ls -l
    rules:
      - exists:
        - material/mkdocs_theme.yml

  build:
    only:
      - main
#    refs:
#      - master
#      - merge_requests
    tags:
      - mkdocs
    stage: texdocs
    script:
      - echo $CI_PROJECT_NAME
      - pwd
      - ls -alZ
      - hostname -f
      - whoami & id
