  check:
    tags:
      - mkdocs
    rules:
      - exists:
          - material/mkdocs_theme.yml
    script:
      - echo "exist"
      - ls -l
      - echo $CI_BUILDS_DIR
      - ll -l $CI_BUILDS_DIR

  build:
    only:
      - main
#    refs:
#      - master
#      - merge_requests
    tags:
      - mkdocs
    script:
      - echo $CI_PROJECT_NAME
      - pwd
      - ls -alZ
      - hostname -f
      - whoami & id
