  01-check:
    tags:
      - mkdocs
    rules:
      - exists:
          - material/mkdocs_theme.yml
    script:
      - echo "exist"
      - ls -l
      - echo $CI_BUILDS_DIR
      - ls -l $CI_BUILDS_DIR

  02-build:
    only:
      - main
    refs:
      - main
      - merge_requests
    tags:
      - mkdocs
    script:
      - sudo -u mkdocs mkdocs build -c -f texdocs.yml -d /var/www/base/docs/Ansible-pull
