site_name: "Create systemd units for ansible-pull"
site_url: "https://D34m0nN0n3.github.io/ansible-ssr-pull/"
site_author: "Dmitriy Prigoda"
site_description: >-
  "Создание и активация сервиса и таймера ansible-pull"

repo_name: D34m0nN0n3/ansible-ssr-pull
repo_url: https://github.com/D34m0nN0n3/ansible-ssr-pull
edit_uri: ""

use_directory_urls: false

copyright: Copyright &copy; <a href="https://github.com/D34m0nN0n3">Dmitriy Prigoda</a>.

nav:
    - Общее описание: 'index.md'
    - Описание роли:
        - infra-system.linux.os.ansible-pull: 'pull.md'
    - Дополнительные материалы: 'seealso.md'

plugins:
  - autolinks
  - autozip
  - search:
      lang:
        - en
        - ru
  - section-index
  - table-reader
  - thumbnails:
      style: margin-top:5px;margin-bottom:5px;margin-right:25px  
  - git-revision-date-localized
  - git-revision-date
  - macros
  - minify:
      minify_html: true
  - pdf-export:
      media_type: print
      combined: true
      combined_output_path: pdf/Create_systemd_units_for_ansible-pull.pdf
      theme_handler_path: theme-handler/material.py

theme:
  name: material
  custom_dir: material
  language: ru
  features:
    - content.tabs.link
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/img/favicon/favicon.png
  logo: assets/img/logo/logo.svg

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown_blockdiag:
      format: svg
  - markdown_include.include
  - markdown.extensions.attr_list 
