---
- name: Create systemd service & timer
  template:
    src: "ansible-pull.{{ item }}.j2"
    dest: "/etc/systemd/system/ansible-pull{% if include_vars.name is defined %}-{{ include_vars.name | default('') }}{% endif %}.{{ item }}"
    owner: root
    group: root
    mode: "0644"
    seuser: system_u
    serole: object_r
    setype: systemd_unit_file_t
  loop: "{{ units }}"
