---
- name: Install local git & ansible-pull
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - git
      - ansible

- name: Ensure group pull-runner exists
  group:
    state: present
    system: yes
    name: pull-runner

- name: Create user pull-runner
  user:
    state: present
    system: yes
    name: pull-runner
    group: pull-runner
    shell: "/sbin/nologin"

- name: Create sudoers rules for pull-runner
  template:
    src: "pull-runner.j2"
    dest: "/etc/sudoers.d/pull-runner"
    owner: root
    group: root
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: etc_t

- include_tasks: add-units.yml
  loop: "{{ ansible_pull_repo }}"
  loop_control:
    loop_var: include_vars

- name: Create vault ID
  template:
    src: "vault.j2"
    dest: "/etc/ansible/vault-{{ item.id_vault }}"
    owner: root
    group: pull-runner
    mode: "0640"
    seuser: system_u
    serole: object_r
    setype: etc_t
  loop: "{{ ansible_pull_secret }}"
  when: ansible_pull_secret is defined

- name: Enable timers
  systemd:
    name: "ansible-pull{% if item.name is defined %}-{{ item.name | default('') }}{% endif %}.timer"
    state: started
    enabled: yes
    daemon_reload: yes
  loop: "{{ ansible_pull_repo }}"
...
